name: StreamEast Scraper
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install firefox
          playwright install-deps
      - name: Run scraper
        run: python stream.py
