name: Run Python Script
on: [push, workflow_dispatch]  # Runs on push or manual trigger
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify Python version
      - name: Run Python Script
        run: python stream.py
