name: FFFFFFF

on:
  workflow_dispatch:  # Run manually only for now

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 🛠 Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: 🚀 XRun FFmpeg HLS to RTMP Python script
        run: python3 ffff.py
