name: FSTV M3U8 and Post Data

on:
  schedule:
    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch:  # manual trigger

jobs:
  extract-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          playwright install chromium

      - name: Run extractor and post script
        run: |
          python fstvlive.py
