name: PPV Stream Scraper

on:
  schedule:
    # Runs every 25 minutes (uses a trick to spread over an hour)
    - cron: '*/25 * * * *'
  workflow_dispatch:  # Manual run support

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp playwright
          playwright install firefox

      - name: Run scraper script
        run: python pp.py
